### ISSUE TITLE
🚀 [Feature]: Add golangci-lint

### ISSUE THREAD

**Issue by leonklingele** [gofiber/utils#68]
### Feature Description

Should use the same config as on the main repo.

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by gaby** [comment]
Maybe we should move this config to https://github.com/gofiber/.github

**Comment by ReneWerner87** [comment]
yes for this we have the task 
https://github.com/orgs/gofiber/projects/3?pane=issue&itemId=45462785

**Comment by gaby** [comment]
I'm almost done with this one

**Comment by gaby** [comment]
Fixed by #79
